// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import frc.robot.RobotMap;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

/**
 *
 */
public class Climber extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX shoulderCtr;
    private final WPI_TalonSRX winchCtr;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Climber() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    shoulderCtr = new WPI_TalonSRX(RobotMap.SHOULDER_CAN_ID);
    addChild("ShoulderCtr",shoulderCtr);
    shoulderCtr.setInverted(false);
        
    winchCtr = new WPI_TalonSRX(RobotMap.WINCH_CAN_ID);
    addChild("WinchCtr",winchCtr);
    winchCtr.setInverted(false);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void stop_winch() {
        winchCtr.set(ControlMode.PercentOutput, 0);
      }

      public void stop_shoulder() {
        shoulderCtr.set(ControlMode.PercentOutput, 0);
      }
      public void up_winch() {
        winchCtr.set(ControlMode.PercentOutput, RobotMap.WINCH_SPEED);
      }

      public void up_shoulder() {
        shoulderCtr.set(ControlMode.PercentOutput, -RobotMap.SHOULDER_SPEED);
      }
      public void down_winch() {
        winchCtr.set(ControlMode.PercentOutput, -RobotMap.WINCH_SPEED);
      }

      public void down_shoulder() {
        shoulderCtr.set(ControlMode.PercentOutput, RobotMap.SHOULDER_SPEED);
      }
}

